// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkxjkesdzahehwhtfatw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhreGprZXNkemFoZWh3aHRmYXR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3Mjg4ODksImV4cCI6MjA3MDMwNDg4OX0.M4PYidChztEUxK1-QRi8HEpysvybOw-G5u8EcNYydU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});